import type {Category} from "../types/Category.ts";
import type {Product} from "../types/Product.ts";

export const mockCategories: Category[] = [
    { id: '1', name: 'Электроника', parent_id: '0' },
    { id: '2', name: 'Книги', parent_id: '0' },
    { id: '3', name: 'Одежда', parent_id: '0' },
    { id: '4', name: 'Бытовая техника', parent_id: '0' },
    { id: '5', name: 'Игрушки', parent_id: '0' },
    { id: '6', name: 'Смартфоны', parent_id: '1' },
    { id: '7', name: 'Ноутбуки', parent_id: '1' },
    { id: '8', name: 'Аудиотехника', parent_id: '1' },
    { id: '9', name: 'Художественная литература', parent_id: '2' },
    { id: '10', name: 'Научная литература', parent_id: '2' },
    { id: '11', name: 'Мужская одежда', parent_id: '3' },
    { id: '12', name: 'Женская одежда', parent_id: '3' },
    { id: '13', name: 'Верхняя одежда', parent_id: '3' },
    { id: '14', name: 'Холодильники', parent_id: '4' },
    { id: '15', name: 'Стиральные машины', parent_id: '4' },
    { id: '16', name: 'Мелкая техника для кухни', parent_id: '4' },
    { id: '17', name: 'Конструкторы', parent_id: '5' },
    { id: '18', name: 'Мягкие игрушки', parent_id: '5' },
    { id: '19', name: 'Настольные игры', parent_id: '5' }
];

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'iPhone 15 Pro',
        id_category: '6',
        id_category_parent: '1',
        price: 39999,
        quantity: 50,
        id_producer: 'Apple',
        description: 'iPhone 15 Pro с передовыми функциями и отличным качеством камеры.',
        image: 'https://via.placeholder.com/400x400?text=iPhone+15+Pro',
        preview_image: 'https://via.placeholder.com/200x200?text=iPhone+15+Pro'
    },
    {
        id: '2',
        name: 'Samsung Galaxy S23',
        id_category: '6',
        id_category_parent: '1',
        price: 28999,
        quantity: 70,
        id_producer: 'Samsung',
        description: 'Современный смартфон с мощной камерой и производительным процессором.',
        image: 'https://via.placeholder.com/400x400?text=Samsung+Galaxy+S23',
        preview_image: 'https://via.placeholder.com/200x200?text=Samsung+Galaxy+S23'
    },
    {
        id: '3',
        name: 'MacBook Air M2',
        id_category: '7',
        id_category_parent: '1',
        price: 54999,
        quantity: 30,
        id_producer: 'Apple',
        description: 'Лёгкий и мощный ноутбук для работы и творчества.',
        image: 'https://via.placeholder.com/400x400?text=MacBook+Air+M2',
        preview_image: 'https://via.placeholder.com/200x200?text=MacBook+Air+M2'
    },
    {
        id: '4',
        name: 'Dell XPS 13',
        id_category: '7',
        id_category_parent: '1',
        price: 47999,
        quantity: 40,
        id_producer: 'Dell',
        description: 'Ультратонкий ноутбук с отличным экраном и производительностью.',
        image: 'https://via.placeholder.com/400x400?text=Dell+XPS+13',
        preview_image: 'https://via.placeholder.com/200x200?text=Dell+XPS+13'
    },
    {
        id: '5',
        name: 'Sony WH-1000XM5',
        id_category: '8',
        id_category_parent: '1',
        price: 10999,
        quantity: 60,
        id_producer: 'Sony',
        description: 'Беспроводные наушники с активным шумоподавлением.',
        image: 'https://via.placeholder.com/400x400?text=Sony+WH-1000XM5',
        preview_image: 'https://via.placeholder.com/200x200?text=Sony+WH-1000XM5'
    },
    {
        id: '6',
        name: 'Краткая история времени',
        id_category: '10',
        id_category_parent: '2',
        price: 349,
        quantity: 80,
        id_producer: 'Eksmo',
        description: 'Знаменитая книга Стивена Хокинга о природе Вселенной.',
        image: 'https://via.placeholder.com/400x400?text=Краткая+история+времени',
        preview_image: 'https://via.placeholder.com/200x200?text=Краткая+история+времени'
    },
    {
        id: '7',
        name: 'Властелин колец',
        id_category: '9',
        id_category_parent: '2',
        price: 499,
        quantity: 120,
        id_producer: 'AST',
        description: 'Эпическая фэнтези-трилогия Дж. Р. Р. Толкина.',
        image: 'https://via.placeholder.com/400x400?text=Властелин+колец',
        preview_image: 'https://via.placeholder.com/200x200?text=Властелин+колец'
    },
    {
        id: '8',
        name: 'Мужская футболка Nike',
        id_category: '11',
        id_category_parent: '3',
        price: 899,
        quantity: 150,
        id_producer: 'Nike',
        description: 'Комфортная спортивная футболка для мужчин.',
        image: 'https://via.placeholder.com/400x400?text=Мужская+футболка+Nike',
        preview_image: 'https://via.placeholder.com/200x200?text=Мужская+футболка+Nike'
    },
    {
        id: '9',
        name: 'Женская куртка Adidas',
        id_category: '12',
        id_category_parent: '3',
        price: 1999,
        quantity: 100,
        id_producer: 'Adidas',
        description: 'Стильная и теплая куртка для женщин.',
        image: 'https://via.placeholder.com/400x400?text=Женская+куртка+Adidas',
        preview_image: 'https://via.placeholder.com/200x200?text=Женская+куртка+Adidas'
    },
    {
        id: '10',
        name: 'LEGO Star Wars',
        id_category: '17',
        id_category_parent: '5',
        price: 1299,
        quantity: 80,
        id_producer: 'LEGO',
        description: 'Конструктор LEGO по мотивам Star Wars.',
        image: 'https://via.placeholder.com/400x400?text=LEGO+Star+Wars',
        preview_image: 'https://via.placeholder.com/200x200?text=LEGO+Star+Wars'
    },
    { id: '11', name: 'Холодильник LG', id_category: '14', id_category_parent: '4', price: 18999, quantity: 20, id_producer: 'LG', description: 'Современный холодильник с большой вместимостью.', image: 'https://via.placeholder.com/400x400?text=Холодильник+LG', preview_image: 'https://via.placeholder.com/200x200?text=Холодильник+LG' },
    { id: '12', name: 'Стиральная машина Bosch', id_category: '15', id_category_parent: '4', price: 13999, quantity: 25, id_producer: 'Bosch', description: 'Энергосберегающая стиральная машина с большим количеством программ.', image: 'https://via.placeholder.com/400x400?text=Стиральная+машина+Bosch', preview_image: 'https://via.placeholder.com/200x200?text=Стиральная+машина+Bosch' },
    { id: '13', name: 'Миксер Philips', id_category: '16', id_category_parent: '4', price: 1499, quantity: 60, id_producer: 'Philips', description: 'Компактный кухонный миксер для приготовления различных блюд.', image: 'https://via.placeholder.com/400x400?text=Миксер+Philips', preview_image: 'https://via.placeholder.com/200x200?text=Миксер+Philips' },
    { id: '14', name: 'Мягкий медведь Teddy', id_category: '18', id_category_parent: '5', price: 499, quantity: 200, id_producer: 'TeddyCo', description: 'Плюшевая мягкая игрушка для детей.', image: 'https://via.placeholder.com/400x400?text=Мягкий+медведь+Teddy', preview_image: 'https://via.placeholder.com/200x200?text=Мягкий+медведь+Teddy' },
    { id: '15', name: 'Настольная игра Catan', id_category: '19', id_category_parent: '5', price: 899, quantity: 120, id_producer: 'Catan', description: 'Популярная настольная игра для всей семьи.', image: 'https://via.placeholder.com/400x400?text=Настольная+игра+Catan', preview_image: 'https://via.placeholder.com/200x200?text=Настольная+игра+Catan' },
    { id: '16', name: 'Canon EOS R6', id_category: '1', id_category_parent: '1', price: 74999, quantity: 15, id_producer: 'Canon', description: 'Полнокадровая беззеркальная камера с высокой скоростью съемки.', image: 'https://via.placeholder.com/400x400?text=Canon+EOS+R6', preview_image: 'https://via.placeholder.com/200x200?text=Canon+EOS+R6' },
    { id: '17', name: 'Google Pixel 8', id_category: '6', id_category_parent: '1', price: 25999, quantity: 50, id_producer: 'Google', description: 'Современный смартфон с чистым Android и отличной камерой.', image: 'https://via.placeholder.com/400x400?text=Google+Pixel+8', preview_image: 'https://via.placeholder.com/200x200?text=Google+Pixel+8' },
    { id: '18', name: 'Asus ROG Zephyrus', id_category: '7', id_category_parent: '1', price: 61999, quantity: 20, id_producer: 'Asus', description: 'Игровой ноутбук с мощной видеокартой и охлаждением.', image: 'https://via.placeholder.com/400x400?text=Asus+ROG+Zephyrus', preview_image: 'https://via.placeholder.com/200x200?text=Asus+ROG+Zephyrus' },
    { id: '19', name: 'Книга: Гарри Поттер', id_category: '9', id_category_parent: '2', price: 399, quantity: 90, id_producer: 'Bloomsbury', description: 'Популярная серия книг о приключениях юного волшебника.', image: 'https://via.placeholder.com/400x400?text=Гарри+Поттер', preview_image: 'https://via.placeholder.com/200x200?text=Гарри+Поттер' },
    { id: '20', name: 'Женское платье Zara', id_category: '12', id_category_parent: '3', price: 1299, quantity: 110, id_producer: 'Zara', description: 'Элегантное платье для повседневной носки.', image: 'https://via.placeholder.com/400x400?text=Женское+платье+Zara', preview_image: 'https://via.placeholder.com/200x200?text=Женское+платье+Zara' },
];